### ISSUE TITLE
How do I install Timeshift?

### ISSUE THREAD

**Issue by coreybruce** [tarkah/solus-timeshift#1]
Got no idea how to install Timeshift, would you mind adding instructions please

**Comment by tarkah** [comment]
I've created a release with the .eopkg. Just use eopkg to install. Or you can download source and use ypkg to build and install. 

Note I haven't updated this in a few months, so it's still on 18.6.1

**Comment by Christoph3PT** [comment]
Tried to install it , gives error about the dependency dcron .

Best regards,

**Comment by tarkah** [comment]
@ghost, it appears dcron has been made inactive in the Solus repository. Seems like they only want to support systemd.timers.  

See [https://github.com/teejee2008/timeshift/issues/201](https://github.com/teejee2008/timeshift/issues/201)

I will probably take down this repository since Timeshift will no longer work without dcron.  If Timeshift ever gets updated to support systemd.timers, I will repackage.
